name: Update calendar events

on:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch: 

jobs:
  update-calendar:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with: 
          ref: production
      - uses: actions/setup-node@v3
        with:
          node-version: 18
      - run: npm install && node sync.js "${{secrets.CALENDAR_URL}}" "../../_data/calendar.yaml"
        working-directory: _utils/calendar_sync
      - uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: automated calendar update
