name: Update calendar events

on:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:

jobs:
  update-calendar:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          ref: production
          token: ${{secrets.CALENDAR_PAT}}
      - uses: actions/setup-node@v3
        with:
          node-version: 18
      - run: npm install
        name: prepare npm environment
        working-directory: _utils/calendar_sync
      - run: node sync.js "${{secrets.CALENDAR_URL}}" "../../_data/calendar.yaml"
        name: fetch bdsi calendar events
        working-directory: _utils/calendar_sync
      - run: node ut-events-scraper.js "${{secrets.BMSLAB_EVENTS_URL}}" "bms-lab" "../../_data/bmslab_events.yaml"
        name: fetch bmslab events
        working-directory: _utils/calendar_sync
      - run: node ut-events-scraper.js "${{secrets.DCC_EVENTS_URL}}" "dcc" "../../_data/dcc_events.yaml"
        name: fetch dcc events
        working-directory: _utils/calendar_sync
      - run: node ut-events-scraper.js "${{secrets.DSI_EVENTS_URL}}" "dsi" "../../_data/dsi_events.yaml"
        name: fetch dcc events
        working-directory: _utils/calendar_sync
      - uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: automated calendar update
