name: Build & deploy to development server

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source
        uses: actions/checkout@v4

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 2.7
          bundler-cache: true
          cache-version: 24

      - name: Build static files
        run: bundle exec jekyll build --baseurl /bdsi.utwente.nl --destination _site_dev/

      - name: Create artifact
        uses: actions/upload-pages-artifact@v2
        with:
          name: github-pages-dev
          path: _site_dev/

  deploy:
    needs: build
    permissions:
      pages: write
      id-token: write
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: deploy
        id: deployment
        uses: actions/deploy-pages@v4
        with:
          artifact_name: github-pages-dev
