name: Build & Deploy Jekyll

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - name: Checkout source
        uses: actions/checkout@v2
        with: 
          path: source
      
      - name: Checkout www
        uses: actions/checkout@v2
        with:
          path: www
          ref: www
          
      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 2.6
          bundler-cache: true
          working-directory: source

      - name: Build static files
        run: | 
          cd source
          bundle exec jekyll build
    
      - name: Push to www
        run: |
          rm -rf www/*
          cp -rf source/_site/* www
          cd www
          git config --local user.name jekyll-bot
          git config --local user.email bdsi@utwente.nl
          git commit -am "rebuild for $(echo $GITHUB_SHA | cut -c1-8)"
          git remote -v
          git push origin www
