name: Build & Deploy Jekyll

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:
    
jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - name: Checkout source
        uses: actions/checkout@v2
        with: 
          path: source
      
      - name: Checkout www
        uses: actions/checkout@v2
        with:
          path: www
          ref: www
          
      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 2.7
          bundler-cache: true
          cache-version: 24
          working-directory: source

      - name: Build static files
        run: | 
          cd source
          bundle exec jekyll build

      - name: Check dead links
        run: |
          cd source
          bundle exec htmlproofer --only-4xx --ignore-status-codes "403" --assume-extension --ignore-empty-alt --checks "Links,Images"  ./_site
    
      - name: Push to www
        run: |
          rm -rf www/*
          cp -rf source/_site/* www
          cd www
          git config --local user.name jekyll-bot
          git config --local user.email bdsi@utwente.nl
          git add .
          git commit -am "rebuild for $(echo $GITHUB_SHA | cut -c1-8)"
          git push origin www
