name: Build & deploy to production server

on:
  push:
    branches: [production]
  pull_request:
    branches: [production]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source
        uses: actions/checkout@v4
        with:
          ref: production

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 2.7
          bundler-cache: true
          cache-version: 24

      - name: Build static files for production
        run: bundle exec jekyll build

      - name: Check dead links
        run: bundle exec htmlproofer --only-4xx --ignore-status-codes "403" --assume-extension ".html" --ignore-empty-alt true --ignore-missing-alt true --checks "Links,Images" ./_site

      - name: Create production artifact
        uses: actions/upload-artifact@v4
        with:
          name: github-pages
          path: _site/

  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout www
        uses: actions/checkout@v4
        with:
          path: www
          ref: www

      - name: Fetch pages artifact
        uses: actions/download-artifact@v4
        with:
          name: github-pages
          path: www-new

      - name: Push to www
        run: |
          rm -rf www/*
          cd www
          tar -xvf ../www-new/artifact.tar
          git config --local user.name jekyll-bot
          git config --local user.email bdsi@utwente.nl
          git add .
          git commit -am "rebuild for $(echo $GITHUB_SHA | cut -c1-8)"
          git push origin www
